# A workflow run is made up of one or more jobs
name: Hello

# runs on a trigger
on:
  push:
   branches: [main]
   paths:
    - '**.html'
   
      
# these jobs are inside the workflow and run on based on dependencies
jobs:
  
  greet: 
#this is a github runner/each job runs on a runner
     runs-on: ubuntu-latest
  
     steps:
     
      - name: say hello to users
        run: echo "Hello"
      
      - name: say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: version of python, docker, etc
        run: docker --version && python --version
     







  
